### PR TITLE
Article status and type is now sortable

### PR DESCRIPTION
**Pull request by CWGran**
in dropdown-menus

### CODE REVIEW

**Comment by Matsemann** [comment]
This looks good. One small change is needed, however. In db-changelog.xml, since we are now "live", we cannot change the existing "changesets" as they have already been run on the server. So changes to them wont have any effect.
So the changes should be added to the bottom of the file instead. You can see an example here: 
https://github.com/Studentmediene/Momus/blob/develop/src/main/resources/db-changelog.xml#L507
First adding the new field, and then updating the existing items.

**Comment by Matsemann** [comment]
Ohh, and it's a good idea to count in hundreds for the order. So 100, 200, 300 etc., then we can shuffle them around easily and add new ones inbetween. :)

**Comment by CWGran** [comment]
Will fix :) I just added some random numbers to see that they actually was ordered.

**Comment by Matsemann** [comment]
Har forresten skrevet dokumentasjon på det jeg skrev over nå, slik at det er litt greiere i fremtiden. :)
 https://wiki.smint.no/wiki/Momus_%28IT%29/Database_Versioning

Blir litt norwenglish her.

**Pull request merged**
